# Generated by Django 5.2.6 on 2025-10-13 22:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='HUF', max_length=8)),
                ('description_raw', models.TextField(blank=True)),
                ('description_norm', models.TextField(blank=True)),
                ('counterparty', models.TextField(blank=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('category_id', models.UUIDField(blank=True, null=True)),
                ('is_transfer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ingestion.fileimport')),
            ],
            options={
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['user_id'], name='transaction_user_id_b5bcfd_idx'), models.Index(fields=['booking_date'], name='transaction_booking_76b1f6_idx')],
            },
        ),
    ]
