# Generated by Django 5.2.6 on 2025-10-13 22:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('enabled', models.BooleanField(default=True)),
                ('match_type', models.CharField(choices=[('contains', 'Contains'), ('regex', 'Regex'), ('equals', 'Equals'), ('amount_range', 'Amount Range')], max_length=32)),
                ('match_value', models.TextField()),
                ('action_set_category', models.CharField(blank=True, max_length=64, null=True)),
                ('action_mark_transfer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rules',
                'ordering': ['priority'],
            },
        ),
    ]
