# Generated by Django 5.2.6 on 2025-10-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_category_remove_transaction_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='referenceCount',
            field=models.IntegerField(default=0),
        ),
    ]
