# Generated by Django 5.2.6 on 2025-10-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_category_referencecount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='referenceCount',
            new_name='reference_count',
        ),
    ]
