# Generated by Django 5.2.6 on 2025-10-30 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0006_rename_referencecount_category_reference_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('storage_path', models.TextField(unique=True)),
                ('original_name', models.CharField(max_length=128)),
                ('size_bytes', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reports',
                'indexes': [models.Index(fields=['user_id'], name='reports_user_id_224fd3_idx'), models.Index(fields=['year', 'month'], name='reports_year_f20bf9_idx')],
            },
        ),
    ]
